### ISSUE TITLE
Animation does not work in some variants

### ISSUE THREAD

**Issue by as3lover** [ikcb/animated-tailwindcss#1]
Animation does not work in some cases like hover.

For example, if I add this class:
`hover:animate-shakeX`

This code will be added to the stylesheet:
`.hover\:animate-shakeX:hover{
  -webkit-animation:shakeX;
          animation:shakeX;
}`

But for it to work, it has to be something like this:
`.hover\:animate-shakeX:hover{
  -webkit-animation:shakeX 1s;
          animation:shakeX 1s;
}`

What can be done to solve the problem?

**Comment by brc-dd** [comment]
Firstly, sorry for late reply. Notifications were paused for this repo.  Now coming to your use case, you also need to add:
`hover:animate-animated`

It will add the `animation-duration` property.

[Here is an example.](https://play.tailwindcss.com/XtgUCYJi4n)
