### ISSUE TITLE
Animation on Scroll

### ISSUE THREAD

**Issue by SoyDiego** [ikcb/animated-tailwindcss#125]
Hi, thanks for your code, works perfectly.
But is possible start the animation when the scroll is down?

Thanks and happy new year! :)

**Comment by brc-dd** [comment]
With only CSS it is not possible. You need JS to create an `IntersectionObserver`.

What framework are you using (like simple JS or something like React/Vue)? Depending on that I can provide you some reference on how to do that.

**Comment by SoyDiego** [comment]
> With only CSS it is not possible. You need JS to create an `IntersectionObserver`.
> 
> What framework are you using (like simple JS or something like React/Vue)? Depending on that I can provide you some reference on how to do that.

Thanks for your fast reply. I'm using React.
I appreciate if you can help me, thanks again!

**Comment by brc-dd** [comment]
Just wrote a component to do this using [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer). Clone this repo to test: https://github.com/brc-dd/react-tw-reveal.

```js
// components/Reveal.js

import { Children, cloneElement, createElement } from 'react';
import { useInView } from 'react-intersection-observer';

const RevealCore = ({ children, className }) => {
  const [ref, inView] = useInView({ threshold: 0.1, triggerOnce: true });
  const child = Children.only(children);

  return cloneElement(child, {
    ref,
    className: `${child.props?.className ?? ''} ${
      inView ? `${className} animate-distance-[200px] animate-duration-[1200ms]` : '!opacity-0'
    }`,
  });
};

const Reveal = ({ as, children, effect, ...props }) =>
  createElement(
    as ?? 'div',
    props,
    Children.map(children, (child, index) =>
      RevealCore({
        children: child,
        className: `${effect[index] ?? effect[effect.length - 1]} animate-delay-[${index * 500}ms]`,
      }),
    ),
  );

export default Reveal;
export { RevealCore };

/*
safelist

animate-delay-[500ms]
animate-delay-[1000ms]
animate-delay-[1500ms]
*/
```

See `App.js` file for usage. The complexity of the component can be adjusted depending on your requirements.

**Comment by SoyDiego** [comment]
> Just wrote a component to do this using [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer). Clone this repo to test: https://github.com/brc-dd/react-tw-reveal.
> 
> ```js
> // components/Reveal.js
> 
> import { Children, cloneElement, createElement } from 'react';
> import { useInView } from 'react-intersection-observer';
> 
> const RevealCore = ({ children, className }) => {
>   const [ref, inView] = useInView({ threshold: 0.1, triggerOnce: true });
>   const child = Children.only(children);
> 
>   return cloneElement(child, {
>     ref,
>     className: `${child.props?.className ?? ''} ${
>       inView ? `${className} animate-distance-[200px] animate-duration-[1200ms]` : '!opacity-0'
>     }`,
>   });
> };
> 
> const Reveal = ({ as, children, effect, ...props }) =>
>   createElement(
>     as ?? 'div',
>     props,
>     Children.map(children, (child, index) =>
>       RevealCore({
>         children: child,
>         className: `${effect[index] ?? effect[effect.length - 1]} animate-delay-[${index * 500}ms]`,
>       }),
>     ),
>   );
> 
> export default Reveal;
> export { RevealCore };
> 
> /*
> safelist
> 
> animate-delay-[500ms]
> animate-delay-[1000ms]
> animate-delay-[1500ms]
> */
> ```
> 
> See `App.js` file for usage. The complexity of the component can be adjusted depending on your requirements. You can also just use `RevealCore` for simple use cases. Feel free to customize distance, duration, delay, threshold, etc.
> 
> Demo:
> React.App.-.Google.Chrome.2022-01-01.20-54-56_Trim.mp4

Thanks for your fast reply and help me!!
Works perfectly on my project!! THANKS @brc-dd :D :D :D

**Comment by SoyDiego** [comment]
@brc-dd Hi again, i have could apply your solution and works but i have other little problem and i don't know how can i solved.
When you do scroll, you can see the element that you want animate for miliseconds and then start the animation. Weird effect.
Do you know how can i do to only appear the elements with the animation?
I don't know if i explain well, my english is not good, but you can see here the effect (in the timeline boxes)
https://soydiegov3.netlify.app/

Thanks again for your help

**Comment by brc-dd** [comment]
@SoyDiego The `!opacity-0` class is not working on your site. Try adding it to safelist.

**Comment by SoyDiego** [comment]
> @SoyDiego The `!opacity-0` class is not working on your site. Try adding it to safelist.

Now WORKS PERFECTLY!!, It was my mistake, I used the "tw-" prefix in my tailwind and I forgot to prefix that opacity class. Thanks a lot friend!
