### ISSUE TITLE
Error on deployment (AWS Amplify)

### ISSUE THREAD

**Issue by mmassetti** [ikcb/animated-tailwindcss#2]
I followed the steps that you give in the readme. I was able to use it successfully locally and also I deployed it on Vercel.
Everything works fine there, but I have a problem when I try to deploy it on Amazon Amplify (I have to deploy it there). 
I don't know if you know what it might be due to.
 
Here is the error:

![image](https://user-images.githubusercontent.com/21322269/131731392-bb9c23ca-7de9-41e8-9861-0f1538c73025.png)

![image](https://user-images.githubusercontent.com/21322269/131731308-557d9a54-1590-4e74-b25c-494ae76d6165.png)

I tried setting this on tailwind.config.js, but it's the same:

```
 options: {
      keyframes: true,
  },
```

I would be grateful if you can give me some advice on what to try to make it work.

Thank you!

**Comment by brc-dd** [comment]
It appears that you are using a Node.js version which doesn't support Nullish coalescing operator (??). For now you can try changing your Node version to v14.x or above. I will try to fix this within the week so that it supports older Node versions too.

**Comment by mmassetti** [comment]
Thanks! I changed the Node version and worked!

**Comment by brc-dd** [comment]
Fixed this in the latest release. The configuration should now work on all living Node.js versions (i.e. v12 and above, may work on End-of-Life versions too).
