### ISSUE TITLE
Animações infinitas

### ISSUE THREAD

**Issue by SperandioIcaro** [ikcb/animated-tailwindcss#212]
Uma ideia é adicionar animações "infinitas", por exemplo em uma pagina principal aquelas animações de ondas, gravidade 0 e etc... que tal?

**Comment by brc-dd** [comment]
Sorry if I understood it wrong, are you asking about having a utility class that makes the animations repeat infinitely? If so, then there is already [`animate-infinite`](https://ikcb.org/animated-tailwindcss/docs/animation-iteration-count). This is what that gets added when you toggle that repeat button in [demo](https://ikcb.org/animated-tailwindcss/docs/animations).
